export const Learnsets: {[k: string]: ModdedLearnsetData} = { //All LCs will have Encounter Levels of 5, allowing them to be used in a theoretically cart-accurate LC. 
	puchikoon: {
		learnset: {
			tailwhip: ["1L1"],
			ember: ["1L1"],
			quickattack: ["1L7"], //new legal move for ponyta
			growl: ["1L14"],
			stomp: ["1L21"],
			agility: ["1L28"],
			firespin: ["1L35"],
			takedown: ["1L42", "1M"],
			toxic: ["1M"],
			horndrill: ["1M"],
			bodyslam: ["1M"],
			doubleedge: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			reflect: ["1M"],
			bide: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	mikon: {
		learnset: {
			tailwhip: ["1L1"],
			ember: ["1L1"],
			quickattack: ["1L7"], //new legal move for ponyta
			roar: ["1L14"],
			firespin: ["1L21"],
			confuseray: ["1L28"],
			doubleteam: ["1L35", "1M"],
			flamethrower: ["1L42"],
			toxic: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			rage: ["1M"],
			dig: ["1M"],
			mimic: ["1M"],
			reflect: ["1M"],
			bide: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	konya: {
		learnset: {
			scratch: ["1L1"],
			growl: ["1L1"]
			tailwhip: ["1L7"],
			sandattack: ["1L14"],
			payday: ["1L17", "1M"],
			bite: ["1L19"],
			furyswipes: ["1L24"],
			screech: ["1L30"],
			slash: ["1L34"],
			toxic: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			rage: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	gyopin: {
		learnset: {
			peck: ["1L1"],
			tailwhip: ["1L1"],
			supersonic: ["1L7"],
			hornattack: ["1L12"],
			furyattack: ["1L16"],
			horndrill: ["1L20", "1M"],
			waterfall: ["1L26"],
			agility: ["1L30"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			surf: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	bittybat: {
		learnset: {
			leechlife: ["1L1"],
			supersonic: ["1L1"],
			wingattack: ["1L7"],
			gust: ["1L14"], //new
			confuseray: ["1L18"],
			bite: ["1L22"],
			tackle: ["1L26"], //new
			disable: ["1L30"], //new
			haze: ["1L34"],
			razorwind: ["1M"],
			whirlwind: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			megadrain: ["1M"],
			swift: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	blastyke: {
		learnset: {
			tackle: ["1L1"],
			tailwhip: ["1L1"],
			bubble: ["1L8"],
			watergun: ["1L15", "1M"],
			bite: ["1L22"],
			withdraw: ["1L28"],
			skullbash: ["1L35", "1M"],
			hydropump: ["1L42"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dig: ["1M"],
			reflect: ["1M"],
			surf: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	magnetite: {
		learnset: {
			tackle: ["1L1"],
			sonicboom: ["1L1"],
			thundershock: ["1L30"],
			supersonic: ["1L34"],
			thunderwave: ["1L40", "1M"],
			swift: ["1L46", "1M"],
			screech: ["1L50"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			swift: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	zuduck: {
		learnset: {
			scratch: ["1L1"],
			tailwhip: ["1L1"],
			supersonic: ["1L22"], //new
			disable: ["1L25"],
			confusion: ["1L29"],
			glare: ["1L34"], //new
			furyswipes: ["1L39"],
			psybeam: ["1L41"], //new
			hydropump: ["1L55"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			payday: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dig: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			surf: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
			
			//amnesia: ["1S0"], || uncomment if it doesn't validate for some fucking reason
		},
		encounters: [
			{generation: 1, level: 15}, //assuming you fish one up with a super rod; makes validation easier i think?
		],
	},
	ribbito: {
		learnset: {
			doubleteam: ["1L1", "1M"],
			tailwhip: ["1L1"],
			bubble: ["1L7"],
			meditate: ["1L13"],
			water gun: ["1L19", "1M"],
			swift: ["1L27, 1M"],
			feintattack: ["1L32"],
			substitute: ["1L42", "1M"],
			hydropump: ["1L49"],
			nightslash: ["1L53"],
			megapunch: ["1M"],
			razorwind: ["1M"],
			swordsdance: ["1M"],
			whirlwind: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			payday: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dig: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			metronome: ["1M"],
			psywave: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	croakazuna: {
		learnset: {
			doubleteam: ["1L1", "1M"],
			tailwhip: ["1L1"],
			bubble: ["1L1"],
			meditate: ["1L13"],
			water gun: ["1L19", "1M"],
			swift: ["1L31, 1M"],
			feintattack: ["1L35"],
			substitute: ["1L46", "1M"],
			hydropump: ["1L53"],
			nightslash: ["1L58"],
			megapunch: ["1M"],
			razorwind: ["1M"],
			swordsdance: ["1M"],
			whirlwind: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			hyperbeam: ["1M"],
			payday: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dig: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			metronome: ["1M"],
			psywave: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
		},
	},
	weepamid: {
		learnset: {
			scratch: ["1L1"],
			growl: ["1L1"],
			glare: ["1L10"],
			watergun: ["1L20"],
			slash: ["1L30"],
			dragonrage: ["1L40", "1M"],
			hydropump: ["1L50"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			dig: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			surf: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	bawligua: {
		learnset: {
			scratch: ["1L1"],
			growl: ["1L1"],
			glare: ["1L10"],
			watergun: ["1L20"],
			slash: ["1L30"],
			dragonrage: ["1L40", "1M"],
			hydropump: ["1L50"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			dig: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			surf: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	crythian: {
		learnset: {
			scratch: ["1L1"],
			growl: ["1L1"],
			glare: ["1L10"],
			watergun: ["1L20"],
			slash: ["1L30"],
			dragonrage: ["1L40", "1M"],
			hydropump: ["1L50"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			hyperbeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			dig: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			surf: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	nidoreign: { //Nidoreign is complicated. It's designed to be a convergent evolution, so it can have moves from Nidorina and Nidorino. 
		learnset: {
			scratch: ["1L1", "1L45"], //However, convergent evolution has never existed in Pokemon and thus has no routes on PS. So we have to get a little janky with this.
			growl: ["1L1", "1L45"], //They should remain incompatible with each sex's movesets but hey probably better to just not deal with it at all.
			tail whip: ["1L1", "1L45"],
			bite: ["1L1", "1L45"],
			fury swipes: ["1L1", "1L45"],
			thrash: ["1L50"], //Ensuring Thrash doesn't become incompatible with Nidorino's moves either.
			megapunch: ["1M"],
			megakick: ["1M"],
			toxic: ["1M"],
			horndrill: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			payday: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			rage: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			reflect: ["1M"],
			bide: ["1M"],
			fireblast: ["1M"],
			skullbash: ["1M"],
			rest: ["1M"],
			rockslide: ["1M"],
			substitute: ["1M"],
			surf: ["1M"],
			strength: ["1M"],
		},//Event data could probably be used but you'd need every combination of the 5 Nidorina moves to make it work. Yikes.
	},
	decilla: {
		learnset: {
			substitute: ["1L1", "1M"],
			growl: ["1L1"],
			tackle: ["1L1"],
			screech: ["1L35"],
			rockthrow: ["1L38"],
			roar: ["1L40"],
			rockslide: ["1L43", "1M"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dragonrage: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			skullbash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
		},
		encounters: [
			{generation: 1, level: 30}, //assuming ressurected from a fossil
		],
	},
	gyaoon: {
		learnset: {
			substitute: ["1L1", "1M"],
			growl: ["1L1"],
			tackle: ["1L1"],
			screech: ["1L35"],
			rockthrow: ["1L38"],
			roar: ["1L40"],
			rockslide: ["1L47", "1M"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			dragonrage: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			skullbash: ["1M"],
			hyperbeam: ["1M"],
			fireblast: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
		},
	},
	omega: {
		learnset: {
			tackle: ["1L1"],
			supersonic: ["1L1"],
			metalsound: ["1L1"],
			magnetbomb: ["1L1"],
			slam: ["1L48"],
			flashcannon: ["1L50"],
			irondefense: ["1L55"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			reflect: ["1M"],
			selfdestruct: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			thunderwave: ["1M"],
			explosion: ["1M"],
			triattack: ["1M"],
			strength: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 45}, //I'm imagining a Silph Co. superboss encounter.
		],
	},
	trampel: {
		learnset: {
			tackle: ["1L1"],
			growl: ["1L1"],
			hornattack: ["1L10"],
			stomp: ["1L23"],
			rage: ["1L30", "1M"],
			furyattack: ["1L38"],
			leer: ["1L44"],
			roar: ["1L50"],
			megapunch: ["1M"],
			megakick: ["1M"],
			horndrill: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 21}, //Safari Zone 1%er
		],
	},
	jagg: {
		learnset: {
			bite: ["1L1"],
			leer: ["1L1"],
			watergun: ["1L10", "1M"],
			screech: ["1L19"],
			mirrorshot: ["1L24"],
			hornattack: ["1L29"],
			furyattack: ["1L36"],
			brutalswing: ["1L42"],
			ironhead: ["1L49"],
			hydropump: ["1L55"],
			swordsdance: ["1M"],
			horndrill: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			skullbash: ["1M"],
			surf: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 20}, //Fishing or near Seafoam
		],
	},
	blottle: {
		learnset: {
			constrict: ["1L1"],
			smokescreen: ["1L1"],
			bubble: ["1L8"],
			wrap: ["1L13"],
			poisongas: ["1L19"],
			hypnosis: ["1L23"],
			supersonic: ["1L27"],
			smog: ["1L39"],
			haze: ["1L43"],
			hydropump: ["1L50"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			watergun: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			reflect: ["1M"],
			surf: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	pendraken: {
		learnset: {
			constrict: ["1L1"],
			smokescreen: ["1L1"],
			bubble: ["1L8"],
			wrap: ["1L13"],
			poisongas: ["1L19"],
			hypnosis: ["1L23"],
			supersonic: ["1L27"],
			smog: ["1L39"],
			haze: ["1L43"],
			hydropump: ["1L50"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			watergun: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			dragonrage: ["1M"],
			psychic: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			psywave: ["1M"],
			surf: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	deer: {
		learnset: {
			tackle: ["1L1"],
			sandattack: ["1L14"],
			jumpkick: ["1L16"],
			confusion: ["1L18"],
			thunderwave: ["1L20", "1M"],
			razorleaf: ["1L22"], //yes it learns moves this fast the prototype was cracked
			supersonic: ["1L26"],
			takedown: ["1L29", "1M"],
			quickattack: ["1L33"],
			leer: ["1L37"],
			agility: ["1L41"],
			thrash: ["1L45"],
			growth: ["1L50"], //may remove this to liberate the levels a bit but it seems fine for now
			bodyslam: ["1M"],
			doubleedge: ["1M"],
			megadrain: ["1M"],
			solarbeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			psychic: ["1M"],
			teleport: ["1M"],
			psywave: ["1M"],
			strength: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 18}, //no clue just validate the movepool and do what tajiri said
		],
	},
	barunda: {
		learnset: {
			fairywind: ["1L1"],
			growl: ["1L1"],
			drainingkiss: ["1L1"],
			sweetkiss: ["1L25"],
			confuseray: ["1L31"],
			charm: ["1L37"],
			dazzlinggleam: ["1L43"],
			razorwind: ["1M"],
			whirlwind: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			psychic: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"], //this can probably be cut but it's on the sheet and seemed edge-case-y
			selfdestruct: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			dreameater: ["1M"],
			psywave: ["1M"],
			explosion: ["1M"],
			triattack: ["1M"],
			fly: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 30}, //idk stationary encounter?
		],
	},
	cheep: {
		learnset: {
			bubble: ["1L17"],
			counter: ["1L19", "1L25", "1M"],
			bubblebeam: ["1L21", "1M"],
			lowkick: ["1L23"],
			jumpkick: ["1L32"],
			seismictoss: ["1L34", "1M"],
			waterfall: ["1L36"],
			highjumpkick: ["1L40"],
			strength: ["1L42", "1M"],
			hydropump: ["1L48"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			skyattack: ["1M"],
			surf: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 15}, //super rod
		],
	},
	jabetta: {
		learnset: {
			bubble: ["1L17"], //had the same learn levels iirc
			counter: ["1L19", "1L25", "1M"],
			bubblebeam: ["1L21", "1M"],
			lowkick: ["1L23"],
			jumpkick: ["1L32"],
			seismictoss: ["1L34", "1M"],
			waterfall: ["1L36"],
			highjumpkick: ["1L40"],
			strength: ["1L42", "1M"],
			hydropump: ["1L48"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			skyattack: ["1M"],
			surf: ["1M"],
			hyperbeam: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	cactus: {
		learnset: {
			tackle: ["1L1"],
			sandattack: ["1L1"],
			vinewhip: ["1L7"],
			hornattack: ["1L13"],
			growth: ["1L21"],
			pinmissile: ["1L25"],
			furyattack: ["1L31"],
			feintattack: ["1L39"],
			spikecannon: ["1L45"],
			explosion: ["1L50", "1M"],
			whirlwind: ["1M"],
			megakick: ["1M"],
			horndrill: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			megadrain: ["1M"],
			solarbeam: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			selfdestruct: ["1M"],
			swift: ["1M"],
			triattack: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 17}, //safari zone?
		],
	},
	kotora: {
		learnset: {
			thundershock: ["1L1"],
			leer: ["1L6"],
			roar: ["1L11"],
			quickattack: ["1L17"],
			bite: ["1L28"],
			thunder: ["1L34"],
			agility: ["1L43"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			thunderbolt: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			thunderwave: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 12},
		],
	},
	gaotora: {
		learnset: {
			thundershock: ["1L1"],
			leer: ["1L1"],
			roar: ["1L14"],
			quickattack: ["1L23"],
			bite: ["1L30"],
			thunder: ["1L37"],
			agility: ["1L45"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			thunderbolt: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			thunderwave: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	gorotora: {
		learnset: {
			thundershock: ["1L1"],
			leer: ["1L1"],
			roar: ["1L14"],
			quickattack: ["1L23"],
			bite: ["1L30"],
			thunder: ["1L37"],
			agility: ["1L45"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			thunderbolt: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			thunderwave: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	crocky: {
		learnset: {
			scratch: ["1L1"],
			leer: ["1L1"],
			supersonic: ["1L7"],
			bite: ["1L12"],
			dragonrage: ["1L20", "1M"],
			slash: ["1L24"],
			screech: ["1L30"],
			glare: ["1L38"],
			confuseray: ["1L46"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			watergun: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			cut: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 17},
		],
	},
	gorochu: {
		learnset: { //TEST: Do the Pikachu moves come up?
			thundershock: ["1L1"],
			growl: ["1L1"],
			thunderwave: ["1L1", "1M"],
			sandattack: ["1L53"],
			focusenergy: ["1L57"],
			leer: ["1L60"],
			horndrill: ["1L65", "1M"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			payday: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			skullbash: ["1M"],
			thunderbolt: ["1M"],
			swift: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	guardia: {
		learnset: {
			boneclub: ["1L1"],
			tailwhip: ["1L1"],
			growl: ["1L1"],
			headbutt: ["1L1"],
			leer: ["1L25"],
			focusenergy: ["1L33"],
			thrash: ["1L41"],
			bonemerang: ["1L48"],
			rage: ["1L55", "1M"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleeedge: ["1M"],
			bubblebeam: ["1M"],
			watergun: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			fireblast: ["1M"],
			skullbash: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	totartle: {
		learnset: {
			tackle: ["1L1"],
			tailwhip: ["1L1"],
			bubble: ["1L1"],
			watergun: ["1L18", "1M"],
			bite: ["1L24"],
			withdraw: ["1L31"],
			skullbash: ["1L42", "1M"],
			hydropump: ["1L46"],
			cometpunch: ["1L50"], //new
			leer: ["1L54"], //new
			petaldance: ["1L60"], //new
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			bubblebeam: ["1M"],
			icebeam: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			megadrain: ["1M"],
			solarbeam: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			reflect: ["1M"],
			surf: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	buu: {
		learnset: {
			aurorabeam: ["1L1"],
			leer: ["1L1"],
			mist: ["1L35"],
			disable: ["1L39"],
			icepunch: ["1L42"],
			haze: ["1L48"],
			icebeam: ["1L55", "1M"],
			megapunch: ["1M"],
			megakick: ["1M"],
			bodyslam: ["1M"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			blizzard: ["1M"],
			hyperbeam: ["1M"],
			submission: ["1M"],
			counter: ["1M"],
			seismictoss: ["1M"],
			psychic: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			metronome: ["1M"],
			skullbash: ["1M"],
			psywave: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 32}, //seafoam rare encounter
		],
	},
	kleavor: {
		learnset: {
			quickattack: ["1L1"],
			leer: ["1L17"],
			focusenergy: ["1L20"],
			rockthrow: ["1L27"],
			slash: ["1L29"],
			swordsdance: ["1L35", "1M"],
			agility: ["1L42"],
			wingattack: ["1L50"],
			takedown: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			rockslide: ["1M"],
			cut: ["1M"],
			strength: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1L24", "1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	growlithehisui: {
		learnset: {
			bite: ["1L1"],
			roar: ["1L1"],
			ember: ["1L18"],
			leer: ["1L23"],
			takedown: ["1L30", "1M"],
			rockslide: ["1L35", "1M"],
			agility: ["1L39"],
			flamethrower: ["1L50"],
			bodyslam: ["1M"],
			doubleedge: ["1M"],
			dragonrage: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			reflect: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	arcaninehisui: {
		learnset: {
			bite: ["1L1"],
			roar: ["1L1"],
			ember: ["1L18"],
			leer: ["1L23"],
			takedown: ["1M"],
			rockslide: ["1M"],
			/*agility: ["1L39"], it should not need to learn these, but if the validator screams, uncomment
			flamethrower: ["1L50"],*/ 
			bodyslam: ["1M"],
			doubleedge: ["1M"],
			hyperbeam: ["1M"],
			dragonrage: ["1M"],
			earthquake: ["1M"],
			fissure: ["1M"],
			dig: ["1M"],
			reflect: ["1M"],
			fireblast: ["1M"],
			swift: ["1M"],
			skullbash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	voltorbhisui: {
		learnset: {
			tackle: ["1L1"],
			screech: ["1L1"],
			sonicboom: ["1L17"],
			selfdestruct: ["1L22", "1M"],
			lightscreen: ["1L29"],
			swift: ["1L36", "1M"],
			explosion: ["1L43", "1M"],
			takedown: ["1M"],
			megadrain: ["1M"],
			solarbeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			thunderwave: ["1M"],
			flash: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	electrodehisui: {
		learnset: {
			tackle: ["1L1"],
			screech: ["1L1"],
			sonicboom: ["1L17"],
			selfdestruct: ["1M"],
			//lightscreen: ["1L29"], uncomment if the validate screams
			swift: ["1M"],
			explosion: ["1M"],
			takedown: ["1M"],
			megadrain: ["1M"],
			solarbeam: ["1M"],
			thunderbolt: ["1M"],
			thunder: ["1M"],
			teleport: ["1M"],
			reflect: ["1M"],
			thunderwave: ["1M"],
			flash: ["1M"],
			hyperbeam: ["1M"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
	},
	/*Follow this template, which includes all of RBY's mandatory TMs for easier importing.
	MONSTERNAME: {
		learnset: {
			tailwhip: ["1L1"],
			
			toxic: ["1M"],
			rage: ["1M"],
			mimic: ["1M"],
			doubleteam: ["1M"],
			bide: ["1M"],
			rest: ["1M"],
			substitute: ["1M"],
		},
		encounters: [
			{generation: 1, level: 5},
		],
	},
	*/
};
